volumes:
  minio-data:
  dagster_home:

networks:
  blake:

services:
  minio:
    image: bitnami/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_DEFAULT_BUCKETS: "blake:public"
    volumes:
      - minio-data:/data
    networks:
      - blake

  dagster-dev:
    develop:
      watch:
        - action: sync
          path: .
          target: /blake
    build:
      context: .
      dockerfile: ./containers/dagster/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - dagster_home:/dagster_home
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_ENDPOINT_URL: http://minio:9000
      DAGSTER_PIPES_BUCKET: blake

    depends_on:
      - minio
