services:
  dagster_blake_postgresql:
    image: postgres:11
    container_name: dagster_blake_postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - dagster_blake_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 10s
      timeout: 8s
      retries: 5

  dagster_blake_user_code:
    build:
      context: .
      dockerfile: ./containers/dagster/Dockerfile
    container_name: dagster_blake_user_code
    image: dagster_blake_user_code_image
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "dagster_blake_user_code_image"
    networks:
      - dagster_blake_network

  dagster_blake_webserver:
    build:
      context: containers/dagster/
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: dagster_blake_webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes: # Make docker client accessible so we can terminate containers from the webserver
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_blake_network
    depends_on:
      dagster_blake_postgresql:
        condition: service_healthy
      dagster_blake_user_code:
        condition: service_started

  dagster_blake_daemon:
    build:
      context: containers/dagster/
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_blake_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_ENDPOINT_URL: http://minio:9000
      MINIO_HOST: minio
      MINIO_PORT: 9000
      DAGSTER_PIPES_BUCKET: blake
      BREWERIES_URL: https://api.openbrewerydb.org/v1
      DUCKDB_DATABASE: data/staging/data.duckdb
      SPARK_URL: spark://spark:7077
    volumes: # Make docker client accessible so we can launch:working_dir: dir containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - dagster_blake_network
    depends_on:
      dagster_blake_postgresql:
        condition: service_healthy
      dagster_blake_user_code:
        condition: service_started

networks:
  dagster_blake_network:
    driver: bridge
    name: dagster_blake_network
